// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260227035840_SeedUserDataInitial")]
    partial class SeedUserDataInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Domain.RefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessTokenJti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReplacedByRefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokenRecords");
                });

            modelBuilder.Entity("Shared.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 39, 655, DateTimeKind.Utc).AddTicks(3850),
                            Email = "trunghau@mstsoftware.vn",
                            Name = "Mai Trung Hau",
                            Password = "$2a$11$sUjZJZ3Bc3y.mS.h0qEhFee7nP0dH8.uAH3TV6WJB39Of2B/G0YyC",
                            Role = "admin",
                            UpdatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 39, 655, DateTimeKind.Utc).AddTicks(3850)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 39, 753, DateTimeKind.Utc).AddTicks(2990),
                            Email = "john@example.com",
                            Name = "John Doe",
                            Password = "$2a$11$TY2UPwObEPY4Hz.7Bb7MFeGYfBL8t1nLdrhk/n6HDsTq9xh3NswRi",
                            Role = "user",
                            UpdatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 39, 753, DateTimeKind.Utc).AddTicks(2990)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 39, 853, DateTimeKind.Utc).AddTicks(9800),
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            Password = "$2a$11$AthO.7/844G2T0U1x3f4VeVhWiecgqNmxC/YBkzjy2pttm2A.884y",
                            Role = "user",
                            UpdatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 39, 853, DateTimeKind.Utc).AddTicks(9800)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 39, 950, DateTimeKind.Utc).AddTicks(2120),
                            Email = "bob@example.com",
                            Name = "Bob Johnson",
                            Password = "$2a$11$BXhLlh2MYdAYSaF6kh.bK.QmYpiPxRF.wlbMa9sm2AxtG2B58QSJO",
                            Role = "user",
                            UpdatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 39, 950, DateTimeKind.Utc).AddTicks(2120)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 40, 46, DateTimeKind.Utc).AddTicks(6810),
                            Email = "alice@example.com",
                            Name = "Alice Williams",
                            Password = "$2a$11$4qSfBzrs/FgqvDMu9UmCq.Zm5Luk/xypXTxW.DDcA.m5SGQwlGt5e",
                            Role = "user",
                            UpdatedAtUTC = new DateTime(2026, 2, 27, 3, 58, 40, 46, DateTimeKind.Utc).AddTicks(6810)
                        });
                });

            modelBuilder.Entity("Shared.Domain.RefreshTokenRecord", b =>
                {
                    b.HasOne("Shared.Domain.User", "User")
                        .WithMany("RefreshTokenRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Domain.User", b =>
                {
                    b.Navigation("RefreshTokenRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
